/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import logica.Generador;

/**
 *
 * @author Eleana Hurtado
 */
public class JFrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrPrincipal
     */
    static String metodo;
    
    public JFrPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCongruMixto = new javax.swing.JButton();
        jButtonCongruMultiplicativo = new javax.swing.JButton();
        jButtonFibonacci = new javax.swing.JButton();
        jButtonCuadradosMedios = new javax.swing.JButton();
        jButtonProductosMedios = new javax.swing.JButton();
        jButtonMultiplicarConstante = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabelTitulo.setText("Generador de números rectangulares");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jButtonCongruMixto.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCongruMixto.setText("Congruencial mixto");
        jButtonCongruMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCongruMixtoActionPerformed(evt);
            }
        });

        jButtonCongruMultiplicativo.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCongruMultiplicativo.setText("Congruencial Multiplicativo ");
        jButtonCongruMultiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCongruMultiplicativoActionPerformed(evt);
            }
        });

        jButtonFibonacci.setBackground(new java.awt.Color(204, 255, 255));
        jButtonFibonacci.setText("Fibonacci");
        jButtonFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFibonacciActionPerformed(evt);
            }
        });

        jButtonCuadradosMedios.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCuadradosMedios.setText("Cuadrados Medios");
        jButtonCuadradosMedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadradosMediosActionPerformed(evt);
            }
        });

        jButtonProductosMedios.setBackground(new java.awt.Color(204, 255, 255));
        jButtonProductosMedios.setText("Productos Medios");
        jButtonProductosMedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosMediosActionPerformed(evt);
            }
        });

        jButtonMultiplicarConstante.setBackground(new java.awt.Color(204, 255, 255));
        jButtonMultiplicarConstante.setText("Multiplicador constante");
        jButtonMultiplicarConstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarConstanteActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCongruMixto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonCongruMultiplicativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addComponent(jButtonFibonacci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonCuadradosMedios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProductosMedios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonMultiplicarConstante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonCongruMixto)
                .addGap(18, 18, 18)
                .addComponent(jButtonCongruMultiplicativo)
                .addGap(18, 18, 18)
                .addComponent(jButtonFibonacci)
                .addGap(18, 18, 18)
                .addComponent(jButtonCuadradosMedios)
                .addGap(18, 18, 18)
                .addComponent(jButtonProductosMedios)
                .addGap(18, 18, 18)
                .addComponent(jButtonMultiplicarConstante)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCongruMultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCongruMultiplicativoActionPerformed
        // TODO add your handling code here:
        metodo = "multiplicativo";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCongruMultiplicativoActionPerformed

    private void jButtonCongruMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCongruMixtoActionPerformed
        // TODO add your handling code here:
        
        metodo="mixto";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCongruMixtoActionPerformed

    private void jButtonFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFibonacciActionPerformed
        // TODO add your handling code here:
        metodo="fibonacci";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFibonacciActionPerformed

    private void jButtonCuadradosMediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadradosMediosActionPerformed
        // TODO add your handling code here:
        metodo="cuadradosMedios";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCuadradosMediosActionPerformed

    private void jButtonProductosMediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosMediosActionPerformed
        // TODO add your handling code here:
        metodo = "productosMedios";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonProductosMediosActionPerformed

    private void jButtonMultiplicarConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarConstanteActionPerformed
        // TODO add your handling code here:
        metodo = "multiplicarConstante";
        JFrMostrarResultados mostrar = new JFrMostrarResultados();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMultiplicarConstanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fol     
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCongruMixto;
    private javax.swing.JButton jButtonCongruMultiplicativo;
    private javax.swing.JButton jButtonCuadradosMedios;
    private javax.swing.JButton jButtonFibonacci;
    private javax.swing.JButton jButtonMultiplicarConstante;
    private javax.swing.JButton jButtonProductosMedios;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
